# Окружение
env:
  es6: true
  node: true

# Используем airbnb-base длябазовой конфигурации
extends: 'airbnb-base'

parserOptions:
  ecmaVersion: latest
  sourceType: module

# правила
rules:
  no-console: 0
  import/extensions: 
    - error
    - ignorePackages
    - js: always
  linebreak-style: 0


  # импорт
  settings:
  'import/extensions':
    - js
    - jsx
    - ts
    - tsx
  'import/no-unresolved': 'error'
  'import/named': 'error'
  'import/default': 'error'
  'import/namespace': 'error'
  'import/export': 'error'
  'import/extensions': ['error', 'ignorePackages']
  'import/newline-after-import': 'error'
  'import/no-absolute-path': 'error'
  'import/no-dynamic-require': 'error'
  'import/no-self-import': 'error'
  'import/no-cycle': 'error'
  'import/no-useless-path-segments': 'error'
  'import/no-extraneous-dependencies': [
    'error',
    { devDependencies: ['**/*.test.js', '**/*.spec.js'] },
  ]