# Окружение
env:
  es6: true
  node: true

# Используем airbnb-base для базовой конфигурации
extends: 'airbnb-base'

# Добавляем правила для парсера
parserOptions:
  ecmaVersion: 2021

# Определяем дополнительные правила
rules:
  # Общие правила оформления
  indent:
    - error
    - 2
  quotes:
    - error
    - single
  semi:
    - error
    - always
  'comma-dangle': [error, 'never']
  'no-console': 'off'
  'no-plusplus': ['error', { allowForLoopAfterthoughts: true }]
  'no-param-reassign': 'off'

  # Правила для импорта
  settings:
  'import/extensions':
    - js
    - jsx
    - ts
    - tsx
  'import/no-unresolved': 'error'
  'import/named': 'error'
  'import/default': 'error'
  'import/namespace': 'error'
  'import/export': 'error'
  'import/extensions': ['error', 'ignorePackages']
  'import/newline-after-import': 'error'
  'import/no-absolute-path': 'error'
  'import/no-dynamic-require': 'error'
  'import/no-self-import': 'error'
  'import/no-cycle': 'error'
  'import/no-useless-path-segments': 'error'
  'import/no-extraneous-dependencies': [
    'error',
    { devDependencies: ['**/*.test.js', '**/*.spec.js'] },
  ]